# Generated by Django 3.1.7 on 2022-01-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=8),
        ),
    ]
