# Generated by Django 3.1.7 on 2022-01-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marksheet', models.CharField(max_length=200)),
                ('twelfth_marksheet', models.CharField(max_length=200)),
                ('leaving_certificate', models.CharField(max_length=200)),
                ('cet_scorecard', models.CharField(max_length=200)),
                ('aadhar_card', models.CharField(max_length=200)),
                ('student_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
