# Generated by Django 3.1.7 on 2022-01-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_studentdocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDocuments',
            new_name='StudentDocument',
        ),
    ]
