# Generated by Django 4.0.2 on 2022-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_sharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharekey',
            name='student_uid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
