# Generated by Django 4.0.2 on 2022-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_faculty_delete_studentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubjectMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_fid', models.CharField(blank=True, max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='branch',
            new_name='department',
        ),
    ]
