# Generated by Django 4.0.2 on 2022-05-17 08:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_studentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 5, 17))]),
        ),
    ]
